In [2]:
!pip install pandas
import pandas as pd

Collecting pandas
  Downloading pandas-2.2.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (89 kB)
Requirement already satisfied: numpy>=1.23.2 in /Users/aps/.local/share/virtualenvs/backend-L_Wnotqq/lib/python3.11/site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/aps/.local/share/virtualenvs/backend-L_Wnotqq/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /Users/aps/.local/share/virtualenvs/backend-L_Wnotqq/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.3-cp311-cp311-macosx_11_0_arm64.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 3.1 MB/s eta 0:00:00a 0:00:01
Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.3 pytz-2024.2 tzdata-2024.2

In [3]:
df = pd.read_csv('/Users/aps/Downloads/transcript_module_4_2024-08-01_to_2024-10-04_batch_1.csv')

In [4]:
df.head(5)

,Session ID,Username,Module Name,Task Name,Message ID,User Message,Bot Message,Created At (UTC),Has Audio,Audio Link
0,217,abcdefg,Version 1: Content Testing,Best Friend,1,NaN,Hello! It's great to see you today. Do you hav...,2024-08-02 14:47:23.174097+00:00,True,https://chatfriend-prod-data.s3.us-east-1.amaz...
1,218,abcdefg,Version 1: Content Testing,Best Friend,1,NaN,Hello! It’s great to see you today. Do you hav...,2024-08-02 14:47:31.222394+00:00,False,NaN
2,223,abcdefg,Version 1: Content Testing,Best Friend,1,NaN,Hello! It's great to see you today. Do you hav...,2024-08-02 18:54:11.162779+00:00,False,NaN
3,223,abcdefg,Version 1: Content Testing,Best Friend,2,Yes,NaN,2024-08-02 18:54:20.968925+00:00,False,NaN
4,223,abcdefg,Version 1: Content Testing,Best Friend,3,NaN,That's wonderful! What is your best friend's n...,2024-08-02 18:54:24.952716+00:00,False,NaN

In [5]:
audio_df = df[df['Has Audio'] == True]

In [6]:
audio_df.head()

,Session ID,Username,Module Name,Task Name,Message ID,User Message,Bot Message,Created At (UTC),Has Audio,Audio Link
0,217,abcdefg,Version 1: Content Testing,Best Friend,1,NaN,Hello! It's great to see you today. Do you hav...,2024-08-02 14:47:23.174097+00:00,True,https://chatfriend-prod-data.s3.us-east-1.amaz...
11,224,abcdefg,Version 1: Content Testing,Best Friend,1,NaN,Hello! It's nice to meet you. Do you have a be...,2024-08-02 18:55:56.395049+00:00,True,https://chatfriend-prod-data.s3.us-east-1.amaz...
12,224,abcdefg,Version 1: Content Testing,Best Friend,2,यह नहीं करने करने करने करने करने,NaN,2024-08-02 18:56:05.933184+00:00,True,https://chatfriend-prod-data.s3.us-east-1.amaz...
13,224,abcdefg,Version 1: Content Testing,Best Friend,3,NaN,I see you're expressing something in Hindi. If...,2024-08-02 18:56:14.760603+00:00,True,https://chatfriend-prod-data.s3.us-east-1.amaz...
14,224,abcdefg,Version 1: Content Testing,Best Friend,4,"Yes, his name is Prashant.",NaN,2024-08-02 18:56:26.901787+00:00,True,https://chatfriend-prod-data.s3.us-east-1.amaz...

In [7]:
user_audio_df = audio_df[audio_df['Bot Message'].isna()]

In [8]:
user_audio_df.head()

,Session ID,Username,Module Name,Task Name,Message ID,User Message,Bot Message,Created At (UTC),Has Audio,Audio Link
12,224,abcdefg,Version 1: Content Testing,Best Friend,2,यह नहीं करने करने करने करने करने,NaN,2024-08-02 18:56:05.933184+00:00,True,https://chatfriend-prod-data.s3.us-east-1.amaz...
14,224,abcdefg,Version 1: Content Testing,Best Friend,4,"Yes, his name is Prashant.",NaN,2024-08-02 18:56:26.901787+00:00,True,https://chatfriend-prod-data.s3.us-east-1.amaz...
16,224,abcdefg,Version 1: Content Testing,Best Friend,6,त्रूष्यलज्,NaN,2024-08-02 18:56:38.271294+00:00,True,https://chatfriend-prod-data.s3.us-east-1.amaz...
18,224,abcdefg,Version 1: Content Testing,Best Friend,8,Thank you very much.,NaN,2024-08-02 18:56:58.470421+00:00,True,https://chatfriend-prod-data.s3.us-east-1.amaz...
64,263,abcdefg,Version 1: Content Testing,Best Friend,2,yes,NaN,2024-08-05 23:38:52.808395+00:00,True,https://chatfriend-prod-data.s3.us-east-1.amaz...

In [9]:
user_audio_df.describe()

       Session ID  Message ID
count   95.000000   95.000000
mean   292.336842   13.831579
std     22.106902   13.084547
min    224.000000    2.000000
25%    281.000000    4.000000
50%    308.000000    8.000000
75%    310.000000   20.000000
max    311.000000   51.000000

In [10]:
user_audio_df.to_csv('user_audio_chatfriend_fall', index=False)